---
apiVersion: v1
kind: Service
metadata:
  name: payments-app
  labels:
    app: payments-app
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
  selector:
    app: payments-app
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: payments-app
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: payments-app
  annotations:
    kubernetes.io/service-account.name: "payments-app"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-app-deployment
  labels:
    app: payments-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-app
  template:
    metadata:
      labels:
        app: payments-app
      annotations:
        vault.hashicorp.com/agent-inject: "true"
        vault.hashicorp.com/role: "payments-app"
        vault.hashicorp.com/agent-inject-token: "true"
    spec:
      serviceAccountName: payments-app
      containers:
        - name: payments-app
          image: payments-app
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
          env:
            - name: VAULT_ADDR
              value: http://vault.vault:8200
            - name: VAULT_TOKEN_FILE
              value: "/vault/secrets/token" 
            - name: VAULT_DB_ROLE
              value: "payments-app" 
            - name: POSTGRES_DB_URL
              value: payments-database
            - name: PAYMENT_PROCESSOR_URL
              value: payments-processor
