version: "3.3"
services:

  payments-app:
    build: ../payments-app
    image: payments-app
    networks:
      vpcbr:
        ipv4_address: 10.5.0.6
    ports:
      - 8081:8081
    volumes:
      - ./vault-agent:/root:r
    entrypoint: ["/bin/sh"]
    command: ["-c", "export VAULT_TOKEN=$$(cat ./agent/client-token) && ./main "]
    environment:
      VAULT_ADDR: "http://vault:8200"
      CONFIG_HOME: "/root/config"

networks:
  vpcbr:
    name: workshop-vault-for-developers_vpcbr
